# Generated by Django 5.0.2 on 2025-12-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'ناموفق'), (2, 'موفق')], default=1)),
                ('contract_number', models.CharField(blank=True, max_length=128, null=True)),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('terminal_id', models.CharField(blank=True, max_length=32, null=True)),
                ('res_number', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('rrn', models.CharField(blank=True, max_length=128, null=True)),
                ('ref_number', models.CharField(blank=True, max_length=128, null=True)),
                ('trace_number', models.CharField(blank=True, max_length=128, null=True)),
                ('secure_pan', models.CharField(blank=True, max_length=128, null=True)),
                ('hashed_card_number', models.CharField(blank=True, max_length=256, null=True)),
                ('callback_status_code', models.IntegerField(blank=True, null=True)),
                ('verify_result_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
