# Generated by Django 5.0.2 on 2024-08-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmemories',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pmemories',
            name='headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
