# Generated by Django 5.0.2 on 2024-08-10 11:29

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_pmemories_created_date_pmemories_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmemories',
            name='img1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='media/memories/'),
        ),
        migrations.AlterField(
            model_name='pmemories',
            name='img2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='media/memories/'),
        ),
    ]
