# Generated by Django 5.0.2 on 2024-08-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_pmemories_img1_alter_pmemories_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='menu_position',
            field=models.CharField(choices=[('1', 'ستون اول'), ('2', 'ستون دوم'), ('3', 'ستون سوم'), ('4', 'ستون چهارم')], default='1', max_length=2),
        ),
    ]
