# Generated by Django 5.0.2 on 2024-08-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_country_menu_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='menu_order',
            field=models.IntegerField(default=1),
        ),
    ]
