# Generated by Django 5.0.2 on 2024-08-20 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_country_menu_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='related_tour_city',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='tour.tour'),
        ),
        migrations.AlterField(
            model_name='spacial_destinations',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.city', unique=True),
        ),
        migrations.AlterField(
            model_name='spacial_destinations',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.country', unique=True),
        ),
    ]
