# Generated by Django 5.0.2 on 2024-08-20 14:03

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_related_tour_city_tour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_faq_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(blank=True, max_length=500, null=True)),
                ('Answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000, null=True)),
                ('Cityfaq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_city', to='tour.city')),
            ],
        ),
        migrations.CreateModel(
            name='hotel_faq_Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(blank=True, max_length=500, null=True)),
                ('Answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10000, null=True)),
                ('Countryfaq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_country', to='tour.country')),
            ],
        ),
    ]
