# Generated by Django 5.0.2 on 2024-08-20 21:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_hotel_faq_city_hotel_faq_country'),
    ]

    operations = [
        
    ]
