# Generated by Django 5.0.2 on 2024-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_tourmenu_meta_description_tourmenu_meta_keywords_and_more'),
    ]

    operations = [

    ]
