# Generated by Django 5.0.2 on 2024-08-24 10:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_package_service_hotel_package_service_m1hotel_and_more'),
    ]

    operations = [

    ]
