# Generated by Django 5.0.2 on 2024-08-26 14:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_tourmenu_meta_description_tourmenu_meta_keywords_and_more'),
    ]

    operations = [


    ]
