# Generated by Django 5.0.2 on 2024-08-26 14:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_tour_spacial_lable_tourmenu_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='spacial_lable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),

    ]
