# Generated by Django 5.0.2 on 2024-08-27 10:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_tourmenu_meta_description_tourmenu_meta_keywords_and_more'),
    ]

    operations = [

    ]
