# Generated by Django 5.0.2 on 2024-10-10 10:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_package_service_hotel_package_service_m1hotel_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='package',
            name='BabyWithBedPrice_doller',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='BabyWithoutBedPrice_doller',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='DoubleBedPrice_doller',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='InfontPrice_doller',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='SingleBedPrice_doller',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tourmenu',
            name='MenuDesc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=3000, null=True),
        ),
    ]
