# Generated by Django 5.0.2 on 2025-01-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_package_service_hotel_package_service_m1hotel_and_more'),
    ]

    operations = [
       
    ]
