# Generated by Django 5.0.2 on 2025-12-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0016_package_service_hotel_package_service_m1hotel_and_more'),
    ]

    operations = [
        migrations.RunSQL("-- existing schema, nothing to do"),
    ]
