# Generated by Django 5.0.2 on 2026-02-23 08:53

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0017_package_service_hotel_package_service_m1hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='service_hotel',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('BB', 'BB'), ('HB', 'HB'), ('FB', 'FB'), ('ALL', 'ALL'), ('U ALL', 'U ALL'), ('max ALL', 'max ALL')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='service_m1hotel',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('BB', 'BB'), ('HB', 'HB'), ('FB', 'FB'), ('ALL', 'ALL'), ('U ALL', 'U ALL'), ('max ALL', 'max ALL')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='service_m2hotel',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('BB', 'BB'), ('HB', 'HB'), ('FB', 'FB'), ('ALL', 'ALL'), ('U ALL', 'U ALL'), ('max ALL', 'max ALL')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='service_m3hotel',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('BB', 'BB'), ('HB', 'HB'), ('FB', 'FB'), ('ALL', 'ALL'), ('U ALL', 'U ALL'), ('max ALL', 'max ALL')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='service_m4hotel',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('BB', 'BB'), ('HB', 'HB'), ('FB', 'FB'), ('ALL', 'ALL'), ('U ALL', 'U ALL'), ('max ALL', 'max ALL')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='service_mhotel',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('BB', 'BB'), ('HB', 'HB'), ('FB', 'FB'), ('ALL', 'ALL'), ('U ALL', 'U ALL'), ('max ALL', 'max ALL')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tourmenu',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tourmenu',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tourmenu',
            name='page_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tourmenu',
            name='show_meu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='Description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=35000, null=True),
        ),
        migrations.AlterField(
            model_name='pmemories',
            name='Message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spacial_destinations',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.city'),
        ),
        migrations.AlterField(
            model_name='spacial_destinations',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.country'),
        ),
    ]
