# Generated by Django 5.0.2 on 2026-03-31 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0018_package_service_hotel_package_service_m1hotel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatName', models.CharField(max_length=500)),
                ('slug', models.SlugField()),
                ('page_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=500, null=True)),
                ('parentCat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Children', to='tour.memorycategory')),
            ],
        ),
    ]
