# Generated by Django 5.0.2 on 2026-03-31 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0019_memorycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmemories',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.memorycategory'),
        ),
        migrations.AddField(
            model_name='pmemories',
            name='metaDescription',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pmemories',
            name='metaKeyword',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pmemories',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
