# Generated by Django 5.0.2 on 2026-04-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0020_pmemories_category_pmemories_metadescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorycategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
