# Generated by Django 5.0.2 on 2026-05-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0021_alter_memorycategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCountryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('document', 'Document')], max_length=20)),
                ('file', models.FileField(upload_to='media/tour_media/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/tour_media/thumbs/%Y/%m/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_media', to='tour.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_media', to='tour.country')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
