# Generated by Django 5.0.2 on 2026-05-03 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0022_citycountrymedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citycountrymedia',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_media', to='tour.city'),
        ),
        migrations.AlterField(
            model_name='citycountrymedia',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_media', to='tour.country'),
        ),
    ]
