# Generated by Django 5.2.13 on 2026-05-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0027_customtourcategory_tour_custom_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtourcategory',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customtourcategory',
            name='country',
        ),
        migrations.AddField(
            model_name='customtourcategory',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='tour_categories', to='tour.city'),
        ),
        migrations.AddField(
            model_name='customtourcategory',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='tour_categories', to='tour.country'),
        ),
        migrations.AddField(
            model_name='customtourcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour/category-images/%Y/%m/'),
        ),
    ]
