# Generated by Django 5.2.13 on 2026-05-18 11:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0028_remove_customtourcategory_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtourcategory',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=3000, null=True),
        ),
    ]
