# Generated by Django 5.2.13 on 2026-05-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0029_alter_customtourcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtourcategory',
            name='meta_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customtourcategory',
            name='meta_keyword',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customtourcategory',
            name='meta_robots',
            field=models.CharField(choices=[('INDEX,FOLLOW', 'Index, Follow - (پیش\u200cفرض) نمایش در نتایج و دنبال کردن لینک\u200cها'), ('INDEX,NOFOLLOW', 'Index, No Follow - نمایش در نتایج، دنبال نکردن لینک\u200cها'), ('NOINDEX,FOLLOW', 'No Index, Follow - عدم نمایش در نتایج، دنبال کردن لینک\u200cها'), ('NOINDEX,NOFOLLOW', 'No Index, No Follow - عدم نمایش در نتایج و دنبال نکردن لینک\u200cها')], default='INDEX,FOLLOW', help_text='تنظیم کنید که این صفحه در گوگل دیده شود یا خیر', max_length=50, verbose_name='وضعیت نمایش در موتورهای جستجو (SEO)'),
        ),
        migrations.AddField(
            model_name='customtourcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
