# Generated by Django 5.2.13 on 2026-05-21 08:57

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0030_customtourcategory_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategoryFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.customtourcategory')),
            ],
        ),
    ]
