# Generated by Django 5.2.13 on 2026-05-23 12:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0031_tourcategoryfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtourcategory',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=35000, null=True),
        ),
    ]
