# Generated by Django 5.0.2 on 2026-06-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0032_alter_customtourcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
