# Generated by Django 5.0.2 on 2026-06-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0034_footer_dollar_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='dollar_rate',
            field=models.IntegerField(default=170000, verbose_name='نرخ دلار به تومان'),
        ),
    ]
