# Generated by Django 5.0.2 on 2026-06-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0035_alter_footer_dollar_rate'),
        ('tour', '0035_tourinterest'),
    ]

    operations = [
    ]
