# Generated by Django 5.0.2 on 2026-07-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0036_merge_0035_alter_footer_dollar_rate_0035_tourinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourinterest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
