# Generated by Django 5.0.2 on 2026-07-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0037_alter_tourinterest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_plan',
            name='infant_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='date_plan',
            name='price_currency',
            field=models.CharField(choices=[('تومان', 'تومان'), ('دلار', 'دلار')], default='تومان', max_length=10),
        ),
    ]
