# Generated by Django 5.0.2 on 2026-07-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0038_date_plan_infant_price_date_plan_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='force_pub',
            field=models.BooleanField(default=False, verbose_name='نمایش تور تاریخ گذشته'),
        ),
    ]
