# Generated by Django 5.0.2 on 2026-08-24 07:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0047_dateplanpackageprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='hotel_sold_out',
            field=models.BooleanField(default=False, verbose_name='تکمیل ظرفیت - هتل اول'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='m1hotel_sold_out',
            field=models.BooleanField(default=False, verbose_name='تکمیل ظرفیت - هتل سوم'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='m2hotel_sold_out',
            field=models.BooleanField(default=False, verbose_name='تکمیل ظرفیت - هتل چهارم'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='m3hotel_sold_out',
            field=models.BooleanField(default=False, verbose_name='تکمیل ظرفیت - هتل پنجم'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='mhotel_sold_out',
            field=models.BooleanField(default=False, verbose_name='تکمیل ظرفیت - هتل دوم'),
        ),
        migrations.AddField(
            model_name='package',
            name='hotel_sold_out',
            field=models.BooleanField(default=False, verbose_name='تکمیل ظرفیت - هتل اول'),
        ),
        migrations.AddField(
            model_name='package',
            name='m1hotel_sold_out',
            field=models.BooleanField(default=False, verbose_name='تکمیل ظرفیت - هتل سوم'),
        ),
        migrations.AddField(
            model_name='package',
            name='m2hotel_sold_out',
            field=models.BooleanField(default=False, verbose_name='تکمیل ظرفیت - هتل چهارم'),
        ),
        migrations.AddField(
            model_name='package',
            name='m3hotel_sold_out',
            field=models.BooleanField(default=False, verbose_name='تکمیل ظرفیت - هتل پنجم'),
        ),
        migrations.AddField(
            model_name='package',
            name='mhotel_sold_out',
            field=models.BooleanField(default=False, verbose_name='تکمیل ظرفیت - هتل دوم'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='about_tour',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='درباره تور'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cancel_policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='قوانین کنسلی'),
        ),
    ]