# Generated by Django 5.0.2 on 2026-09-01 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_hotel_data_meta_robots'),
        ('tour', '0048_dateplanpackageprice_hotel_sold_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='hotel_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_override_hotel', to='hotels.hotel_data', verbose_name='جایگزینی هتل اول برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='عدم نمایش پکیج در این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='m1hotel_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_override_m1hotel', to='hotels.hotel_data', verbose_name='جایگزینی هتل سوم برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='m2hotel_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_override_m2hotel', to='hotels.hotel_data', verbose_name='جایگزینی هتل چهارم برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='m3hotel_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_override_m3hotel', to='hotels.hotel_data', verbose_name='جایگزینی هتل پنجم برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='mhotel_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_override_mhotel', to='hotels.hotel_data', verbose_name='جایگزینی هتل دوم برای این تاریخ'),
        ),
    ]