# Generated by Django 5.0.2 on 2026-09-01 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0049_dateplanpackageprice_hotel_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='exclusive_date_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_packages', to='tour.date_plan', verbose_name='مخصوص این تاریخ برگزاری (خالی یعنی برای همه تاریخ\u200cها)'),
        ),
    ]
