# Generated by Django 5.0.2 on 2026-09-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0050_package_exclusive_date_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_plan_price_currency', to='tour.currency', verbose_name='واحد پول برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='doller_price',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='قیمت ثابت دلاری برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='foreign_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_plan_price_foreign_currency', to='tour.currency', verbose_name='واحد پول خارجی برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='main_pkg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.mainpackage', verbose_name='نوع پکیج برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='service_hotel',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('BB', 'BB'), ('HB', 'HB'), ('FB', 'FB'), ('ALL', 'ALL'), ('U ALL', 'U ALL'), ('max ALL', 'max ALL')], max_length=300, null=True, verbose_name='سرویس هتل اول برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='service_m1hotel',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('BB', 'BB'), ('HB', 'HB'), ('FB', 'FB'), ('ALL', 'ALL'), ('U ALL', 'U ALL'), ('max ALL', 'max ALL')], max_length=300, null=True, verbose_name='سرویس هتل سوم برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='service_m2hotel',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('BB', 'BB'), ('HB', 'HB'), ('FB', 'FB'), ('ALL', 'ALL'), ('U ALL', 'U ALL'), ('max ALL', 'max ALL')], max_length=300, null=True, verbose_name='سرویس هتل چهارم برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='service_m3hotel',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('BB', 'BB'), ('HB', 'HB'), ('FB', 'FB'), ('ALL', 'ALL'), ('U ALL', 'U ALL'), ('max ALL', 'max ALL')], max_length=300, null=True, verbose_name='سرویس هتل پنجم برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='service_mhotel',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('BB', 'BB'), ('HB', 'HB'), ('FB', 'FB'), ('ALL', 'ALL'), ('U ALL', 'U ALL'), ('max ALL', 'max ALL')], max_length=300, null=True, verbose_name='سرویس هتل دوم برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='view',
            field=models.CharField(blank=True, choices=[('', 'انتخاب ویو'), ('land View', 'Land View'), ('Sea View', 'Sea View'), ('Seaside View', 'Seaside View')], max_length=300, null=True, verbose_name='ویو کل پکیج برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='view_hotel',
            field=models.CharField(blank=True, choices=[('', 'انتخاب ویو'), ('land View', 'Land View'), ('Sea View', 'Sea View'), ('Seaside View', 'Seaside View')], max_length=300, null=True, verbose_name='ویو هتل اول برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='view_m1hotel',
            field=models.CharField(blank=True, choices=[('', 'انتخاب ویو'), ('land View', 'Land View'), ('Sea View', 'Sea View'), ('Seaside View', 'Seaside View')], max_length=300, null=True, verbose_name='ویو هتل سوم برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='view_m2hotel',
            field=models.CharField(blank=True, choices=[('', 'انتخاب ویو'), ('land View', 'Land View'), ('Sea View', 'Sea View'), ('Seaside View', 'Seaside View')], max_length=300, null=True, verbose_name='ویو هتل چهارم برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='view_m3hotel',
            field=models.CharField(blank=True, choices=[('', 'انتخاب ویو'), ('land View', 'Land View'), ('Sea View', 'Sea View'), ('Seaside View', 'Seaside View')], max_length=300, null=True, verbose_name='ویو هتل پنجم برای این تاریخ'),
        ),
        migrations.AddField(
            model_name='dateplanpackageprice',
            name='view_mhotel',
            field=models.CharField(blank=True, choices=[('', 'انتخاب ویو'), ('land View', 'Land View'), ('Sea View', 'Sea View'), ('Seaside View', 'Seaside View')], max_length=300, null=True, verbose_name='ویو هتل دوم برای این تاریخ'),
        ),
    ]
