# Generated by Django 5.0.2 on 2026-09-08 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0051_dateplanpackageprice_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150, verbose_name='نام نظردهنده')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ستاره'), (2, '2 ستاره'), (3, '3 ستاره'), (4, '4 ستاره'), (5, '5 ستاره')], default=5, verbose_name='امتیاز')),
                ('text', models.TextField(max_length=1500, verbose_name='متن نظر')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='تاریخ نظر')),
                ('source', models.CharField(choices=[('google', 'گوگل مپ'), ('site', 'ثبت\u200cشده در سایت'), ('instagram', 'اینستاگرام'), ('other', 'سایر')], default='google', max_length=20, verbose_name='منبع نظر')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک اصل نظر (اختیاری)')),
                ('publish', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش (کوچک\u200cتر جلوتر)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tour.country', verbose_name='مربوط به تورهای کدام کشور')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
                'ordering': ['sort_order', '-review_date', '-created_at'],
            },
        ),
    ]
