# Generated by Django 5.0.2 on 2026-09-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0052_tourreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourreview',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=190, null=True, verbose_name='شناسهٔ نظر در گوگل'),
        ),
    ]
