# Generated by Django 5.0.2 on 2026-09-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0053_tourreview_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='transfer_m1hotel',
            field=models.CharField(blank=True, choices=[('', 'بدون ترانسفر'), ('bus', 'اتوبوس'), ('train', 'قطار'), ('flight', 'پرواز داخلی'), ('boat', 'قایق')], max_length=20, null=True, verbose_name='ترانسفر تا هتل سوم'),
        ),
        migrations.AddField(
            model_name='package',
            name='transfer_m2hotel',
            field=models.CharField(blank=True, choices=[('', 'بدون ترانسفر'), ('bus', 'اتوبوس'), ('train', 'قطار'), ('flight', 'پرواز داخلی'), ('boat', 'قایق')], max_length=20, null=True, verbose_name='ترانسفر تا هتل چهارم'),
        ),
        migrations.AddField(
            model_name='package',
            name='transfer_m3hotel',
            field=models.CharField(blank=True, choices=[('', 'بدون ترانسفر'), ('bus', 'اتوبوس'), ('train', 'قطار'), ('flight', 'پرواز داخلی'), ('boat', 'قایق')], max_length=20, null=True, verbose_name='ترانسفر تا هتل پنجم'),
        ),
        migrations.AddField(
            model_name='package',
            name='transfer_mhotel',
            field=models.CharField(blank=True, choices=[('', 'بدون ترانسفر'), ('bus', 'اتوبوس'), ('train', 'قطار'), ('flight', 'پرواز داخلی'), ('boat', 'قایق')], max_length=20, null=True, verbose_name='ترانسفر تا هتل دوم'),
        ),
    ]
