# Generated by Django 5.0.2 on 2026-09-16 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(choices=[('view', 'مشاهده'), ('add', 'ایجاد'), ('edit', 'ویرایش'), ('delete', 'حذف')], max_length=10)),
                ('area', models.CharField(blank=True, default='', max_length=30)),
                ('model_label', models.CharField(blank=True, default='', max_length=100)),
                ('model_title', models.CharField(blank=True, default='', max_length=150)),
                ('object_id', models.CharField(blank=True, default='', max_length=40)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تغییر کاربر',
                'verbose_name_plural': 'تاریخچه تغییرات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.TextField(blank=True, default='')),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دسترسی پشتیبان',
                'verbose_name_plural': 'دسترسی پشتیبان ها',
            },
        ),
    ]
