# Generated by Django 5.0.2 on 2026-09-16 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=40)),
                ('updated_name', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آخرین تغییر',
                'verbose_name_plural': 'آخرین تغییرات',
                'unique_together': {('model_label', 'object_id')},
            },
        ),
    ]
