# Generated by Django 5.0.2 on 2024-08-09 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='visa_request_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trs_number', models.CharField(blank=True, max_length=10, null=True)),
                ('requester_name', models.CharField(max_length=100, verbose_name='Requseter Name')),
                ('requester_family', models.CharField(max_length=100, verbose_name='Requster Family')),
                ('rq_father_name', models.CharField(max_length=100, verbose_name='Father Name')),
                ('rq_father_family', models.CharField(max_length=100, verbose_name='Father Family')),
                ('rq_father_brd', models.DateField(verbose_name='Father Brithday')),
                ('rq_father_brd_location', models.CharField(max_length=100, verbose_name='Father Birth Location')),
                ('rq_mother_name', models.CharField(max_length=100, verbose_name='Mother Name')),
                ('rq_mother_family', models.CharField(max_length=100, verbose_name='Father Family')),
                ('rq_mother_brd', models.DateField(verbose_name='Mother Brithday')),
                ('rq_mother_brd_location', models.CharField(max_length=100, verbose_name='Mother Birth Location')),
                ('address', models.CharField(max_length=300, verbose_name='Requester Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Requester Phone')),
                ('email', models.CharField(max_length=100, verbose_name='Requester E-mail')),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('job_address', models.CharField(max_length=300, verbose_name='Job Address')),
                ('job_phone', models.CharField(max_length=20, verbose_name='Job Phone')),
                ('job_email', models.CharField(max_length=100, verbose_name='Job E-mail')),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='media/visa/passport', verbose_name='Passport Image')),
                ('person_image', models.ImageField(blank=True, null=True, upload_to='media/visa/person', verbose_name='Requester Image')),
                ('visa_file', models.FileField(blank=True, null=True, upload_to='media/visa/resualt')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('old_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_change_date', models.CharField(blank=True, max_length=100, null=True)),
                ('name_change_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('cz_country', models.CharField(blank=True, max_length=100, null=True)),
                ('cz_passport', models.CharField(blank=True, max_length=18, null=True, verbose_name='Passport Number')),
                ('gc_country', models.CharField(blank=True, max_length=100, null=True)),
                ('gc_start_date', models.CharField(blank=True, max_length=11, null=True)),
                ('gc_end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('gc_id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('travel_history', models.CharField(blank=True, max_length=300, null=True)),
                ('social_media', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_family', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_brd_date', models.CharField(blank=True, max_length=11, null=True)),
                ('partner_brd_location', models.CharField(blank=True, max_length=100, null=True)),
                ('uni_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uni_address', models.CharField(blank=True, max_length=200, null=True)),
                ('military_start_date', models.CharField(blank=True, max_length=20, null=True)),
                ('military_end_date', models.CharField(blank=True, max_length=20, null=True)),
                ('military_type', models.CharField(blank=True, max_length=100, null=True)),
                ('military_location', models.CharField(blank=True, max_length=100, null=True)),
                ('travel_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=300, null=True)),
                ('passport_issue', models.DateField(blank=True, null=True)),
                ('passport_expire', models.DateField(blank=True, null=True)),
                ('data_entry_russia', models.DateField(blank=True, null=True)),
                ('relation_degree', models.CharField(blank=True, max_length=150, null=True)),
                ('relation_name', models.CharField(blank=True, max_length=150, null=True)),
                ('relation_family', models.CharField(blank=True, max_length=150, null=True)),
                ('relation_sex', models.CharField(blank=True, max_length=150, null=True)),
                ('relation_Address', models.CharField(blank=True, max_length=150, null=True)),
                ('relation_brd_date', models.CharField(blank=True, max_length=20, null=True)),
                ('orogin_name', models.CharField(blank=True, max_length=150, null=True)),
                ('orogin_address', models.CharField(blank=True, max_length=150, null=True)),
                ('orogin_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('orogin_email', models.CharField(blank=True, max_length=50, null=True)),
                ('orogin_city', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('req_stat', models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Checking', 'Checking'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Approved', 'Approved')], max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_stat', models.BooleanField(default=False)),
                ('marial_stat', models.BooleanField(default=False)),
                ('russia_relative_stat', models.BooleanField(default=False)),
                ('uni_degree_stat', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
