# Generated by Django 5.0.2 on 2025-01-16 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThaiVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trs_number', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('requester_name', models.CharField(max_length=100)),
                ('requester_family', models.CharField(max_length=100)),
                ('rqquester_brd', models.DateField()),
                ('requester_Nationality', models.CharField(max_length=100)),
                ('requester_brd_city', models.CharField(max_length=100)),
                ('requester_country', models.CharField(max_length=100)),
                ('requester_city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_issue', models.DateField(blank=True, null=True)),
                ('passport_expire', models.DateField(blank=True, null=True)),
                ('thai_entry', models.DateField(blank=True, null=True)),
                ('thai_exit', models.DateField(blank=True, null=True)),
                ('marial_stat', models.BooleanField(default=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_company', models.CharField(max_length=100)),
                ('income', models.CharField(max_length=100)),
                ('job_owner', models.BooleanField(default=False)),
                ('thai_trip', models.BooleanField(default=False)),
                ('thai_applied', models.BooleanField(default=False)),
                ('inviter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('inviter_city', models.CharField(blank=True, max_length=100, null=True)),
                ('inviter_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('inviter_email', models.CharField(blank=True, max_length=100, null=True)),
                ('inviter_address', models.CharField(blank=True, max_length=300, null=True)),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='media/visa/thai/passport')),
                ('person_image', models.ImageField(blank=True, null=True, upload_to='media/visa/thai/person')),
                ('person_brd_image', models.ImageField(blank=True, null=True, upload_to='media/visa/thai/brd')),
                ('person_id_image', models.ImageField(blank=True, null=True, upload_to='media/visa/thai/idcard')),
                ('person_hotel_image', models.ImageField(blank=True, null=True, upload_to='media/visa/thai/hotel')),
                ('person_flight_image', models.ImageField(blank=True, null=True, upload_to='media/visa/thai/flight')),
                ('confirmed', models.BooleanField(default=False)),
                ('req_stat', models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Checking', 'Checking'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Approved', 'Approved')], max_length=100, null=True)),
                ('visa_file', models.FileField(blank=True, null=True, upload_to='media/visa/thai/resualt')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('payment_stat', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
