# Generated by Django 5.0.2 on 2025-01-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_thaivisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa_request_item',
            name='relation_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visa_request_item',
            name='requester_id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
