# Generated by Django 5.0.2 on 2024-08-09 09:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('page_image', models.ImageField(blank=True, upload_to='media/pages')),
                ('short_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=2000, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=4000, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('reseller', models.BooleanField(default=False)),
                ('footer_1', models.BooleanField(default=False)),
                ('footer_2', models.BooleanField(default=False)),
                ('footer_3', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('meta_desc', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ads/')),
            ],
        ),
    ]
