# Generated by Django 5.0.2 on 2024-08-09 09:36

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import django_resized.forms
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='hotels/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuTitle', models.CharField(max_length=150)),
                ('MenuDesc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=3000, null=True)),
                ('page_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelName', models.CharField(max_length=500)),
                ('HotelNameEnglish', models.CharField(blank=True, max_length=500, null=True)),
                ('Slug', models.SlugField(max_length=200, unique=True)),
                ('HotelRating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True)),
                ('HotelBookingRate', models.CharField(blank=True, max_length=4, null=True)),
                ('HotelShotDesc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True)),
                ('HotelDesc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10000, null=True)),
                ('HotelRoom', models.CharField(blank=True, max_length=100, null=True)),
                ('HotelAddress', models.CharField(blank=True, max_length=1000, null=True)),
                ('HotelPhone', models.CharField(blank=True, max_length=500, null=True)),
                ('HotelWebSite', models.CharField(blank=True, max_length=1000, null=True)),
                ('HotelLocation', models.CharField(blank=True, max_length=500, null=True)),
                ('HotelMap', models.CharField(blank=True, max_length=1500, null=True)),
                ('HotelFeature', models.BooleanField(default=False)),
                ('HotelOR', models.BooleanField(default=False)),
                ('HotelBB', models.BooleanField(default=False)),
                ('HotelHB', models.BooleanField(default=False)),
                ('HotelFB', models.BooleanField(default=False)),
                ('HotelAll', models.BooleanField(default=False)),
                ('HotelUall', models.BooleanField(default=False)),
                ('HotelMaxAll', models.BooleanField(default=False)),
                ('HotelService', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('پارکینگ', 'پارکینگ'), ('آسانسور', 'آسانسور'), ('شاتل', 'شاتل'), ('ترانسفر فرودگاهی', 'ترانسفر فرودگاهی'), ('فروشگاه در محل', 'فروشگاه در محل'), ('فروشگاه در هتل', 'فروشگاه در هتل'), ('نزدیک به فرودگاه', 'نزدیک به فرودگاه'), ('نزدیک به ساحل', 'نزدیک به ساحل'), ('فضای سبز', 'فضای سبز'), ('ساحل اختصاصی', 'ساحل اختصاصی'), ('اینترنت رایگان در لابی', 'اینترنت رایگان در لابی'), ('سالن کنفرانس', 'سالن کنفرانس'), ('سالن همایش', 'سالن همایش'), ('اجاره ماشین', 'اجاره ماشین'), ('انبار چمدان', 'انبار چمدان'), ('رستوران', 'رستوران'), ('کافی شاپ', 'کافی شاپ'), ('صرافی', 'صرافی'), ('محل مخصوص سیگار کشیدن', 'محل مخصوص سیگار کشیدن'), ('اتاق خانوادگی', 'اتاق خانوادگی'), ('محل سیگار ممنوع', 'محل سیگار ممنوع'), ('امکانات برای معلولین', 'امکانات برای معلولین'), ('لپ تاپ', 'لپ تاپ'), ('ورود حیوانات مجاز', 'ورود حیوانات مجاز')], max_length=5000, null=True)),
                ('RoomService', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('اینترنت رایگان در اتاق', 'اینترنت رایگان در اتاق'), ('تراس/بالکن', 'تراس/بالکن'), ('چای/قهوه ساز', 'چای/قهوه ساز'), ('وان', 'وان'), ('صندوق امانات', 'صندوق امانات'), ('کمد و جالباسی', 'کمد و جالباسی'), ('تهویه مطبوع', 'تهویه مطبوع'), ('حوله و دمپایی', 'حوله و دمپایی'), ('سشوار', 'سشوار'), ('اتو', 'اتو'), ('سنسور دودیاب/ضد حریق', 'سنسور دودیاب/ضد حریق'), ('آلارم بیدار باش', 'آلارم بیدار باش'), ('سیستم گرمایش', 'سیستم گرمایش'), ('تلوزیون/ماهواره', 'تلویزیون/ماهواره'), ('عایق صدا', 'عایق صدا'), ('میز مطالعه', 'میز مطالعه'), ('نور گیر', 'نور گیر'), ('دزدگیر', 'دزدگیر'), ('منظره شهری', 'منظره شهری'), ('آشپزخانه', 'آشپزخانه'), ('لوازم بهداشتي', 'لوازم بهداشتي')], max_length=800, null=True)),
                ('Service', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(' سرویس اتاق 24 ساعته', 'سرویس اتاق 24 ساعته'), ('صبحانه در اتاق', 'صبحانه در اتاق'), ('خدمات پزشکی', 'خدمات پزشکی'), ('خشکشویی', 'خشکشویی'), ('نظافت روزانه', 'نظافت روزانه'), ('پذیرش 24 ساعته', 'پذیرش 24 ساعته'), ('غذای کودک', 'غذای کودک'), ('غذای رژیمی', 'غذای رژیمی'), ('صبحانه', 'صبحانه'), ('خدمات زیبایی', 'خدمات زیبایی')], max_length=800, null=True)),
                ('intertainment', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('استخر روباز', 'استخر روباز'), ('استخر سرپوشیده', 'استخر سرپوشیده'), ('سونا/جکوزی', 'سونا/جکوزی'), ('پارک آبی', 'پارک آبی'), ('حمام ترکی', 'حمام ترکی'), ('ماساژ', 'ماساژ'), ('مینی بار', 'مینی بار'), ('مرکز اسپا و سلامتی', 'مرکز اسپا و سلامتی'), ('استخر کودک', 'استخر کودک'), ('سالن بازی کودکان', 'سالن بازی کودکان'), ('پارک کودک', 'پارک کودک'), (' تفريحات آبي', ' تفريحات آبي'), (' قايقراني', ' قايقراني'), ('غواصی', 'غواصی'), ('سالن بدنسازی', 'سالن بدنسازی'), ('بیلیارد', 'بیلیارد'), ('دارت', 'دارت'), ('تنیس', 'تنیس'), ('کلاس یوگا', 'کلاس یوگا'), ('سولاريوم', 'سولاريوم'), ('ماهيگيري', 'ماهيگيري'), ('اسنک بار', 'اسنک بار'), ('اتاق گیم', 'اتاق گیم'), ('بار', 'بار'), ('پینگ پونگ', 'پینگ پونگ'), ('بولینگ', 'بولینگ'), (' اسکی', ' اسکی'), ('اجراي برنامه هاي شاد', 'اجراي برنامه هاي شاد'), ('موسیقی زنده', 'موسیقی زنده'), ('دی جی', 'دی جی'), ('دوچرخه سواری', 'دوچرخه سواری'), ('گلف', 'گلف'), ('کارائوکه', 'کارائوکه'), ('صندلی ساحلی', 'صندلی ساحلی'), ('کلوپ شبانه', 'کلوپ شبانه')], max_length=800, null=True)),
                ('HotelImage', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='hotel-image')),
                ('metaKeyword', models.TextField(blank=True, max_length=150, null=True)),
                ('metaDescription', models.TextField(blank=True, max_length=300, null=True)),
                ('viewCount', models.IntegerField(blank=True, default=0, null=True)),
                ('htitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('satrap_gte', models.BooleanField(default=False)),
                ('top_rate', models.BooleanField(default=False)),
                ('hotel_price', models.CharField(blank=True, max_length=40, null=True)),
                ('reseve_link', models.CharField(blank=True, max_length=100, null=True)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
