# Generated by Django 5.0.2 on 2024-08-10 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='hotel_data',
            name='HotelTpRate',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
