# Generated by Django 5.0.2 on 2024-08-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_data_hcity_hotel_data_hcountry_and_more'),
        ('tour', '0004_country_menu_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField(max_length=5000)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('hotel_rate', models.CharField(blank=True, max_length=2, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel_data')),
            ],
        ),
    ]
