# Generated by Django 5.0.2 on 2024-08-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_data_hcity_hotel_data_hcountry_and_more'),
        ('tour', '0004_country_menu_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='hotel_comments',
        ),

    ]
