# Generated by Django 5.0.2 on 2024-08-18 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_rename_comments_hotel_comments_hotel_data_hcity_and_more'),
        ('tour', '0005_country_menu_order'),
    ]

    operations = [

    ]
