# Generated by Django 5.0.2 on 2024-08-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hotel_data_hcity_hotel_data_hcountry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_data',
            name='Hcity',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_city', to='tour.city'),
        ),
        migrations.AddField(
            model_name='hotel_data',
            name='Hcountry',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_country', to='tour.country'),
        ),
        migrations.AddField(
            model_name='hotel_data',
            name='HotelMenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel_menu'),
        ),
        migrations.AddField(
            model_name='hotel_images',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel_data'),
        ),
    ]
