# Generated by Django 5.0.2 on 2024-08-27 10:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_hotel_data_hcity_hotel_data_hcountry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_data',
            name='HotelDesc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=25000, null=True),
        ),
    ]
