# Generated by Django 5.0.2 on 2024-08-09 09:36

import ckeditor.fields
import ckeditor_uploader.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500, verbose_name='عنوان مقاله')),
                ('ShortDesc', ckeditor.fields.RichTextField(max_length=6000)),
                ('post_links', ckeditor.fields.RichTextField(blank=True, max_length=6000, null=True)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(max_length=100000)),
                ('Image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='media/post/main-image')),
                ('slug', models.SlugField()),
                ('Publish', models.BooleanField(default=True)),
                ('PubDate', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('metaKeyword', models.TextField(blank=True, max_length=300, null=True)),
                ('metaDescription', models.TextField(blank=True, max_length=150, null=True)),
                ('viewCount', models.IntegerField(blank=True, default=0, null=True)),
                ('ptitle', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': ' مطالب ',
                'verbose_name_plural': ' مطالب ',
            },
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField(max_length=5000)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogposts')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatName', models.CharField(max_length=500)),
                ('slug', models.SlugField()),
                ('page_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=500, null=True)),
                ('parentCat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Children', to='blog.postcategory')),
            ],
        ),
        migrations.AddField(
            model_name='blogposts',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.postcategory'),
        ),
        migrations.CreateModel(
            name='related_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogposts')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_article', to='blog.blogposts')),
            ],
        ),
        migrations.CreateModel(
            name='reply_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField(max_length=5000)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comments')),
            ],
        ),
    ]
