# Generated by Django 5.0.2 on 2025-12-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
