# Generated by Django 5.2.13 on 2026-05-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogposts_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='meta_robots',
            field=models.CharField(choices=[('INDEX,FOLLOW', 'Index, Follow - (پیش\u200cفرض) نمایش در نتایج و دنبال کردن لینک\u200cها'), ('INDEX,NOFOLLOW', 'Index, No Follow - نمایش در نتایج، دنبال نکردن لینک\u200cها'), ('NOINDEX,FOLLOW', 'No Index, Follow - عدم نمایش در نتایج، دنبال کردن لینک\u200cها'), ('NOINDEX,NOFOLLOW', 'No Index, No Follow - عدم نمایش در نتایج و دنبال نکردن لینک\u200cها')], default='INDEX,FOLLOW', help_text='تنظیم کنید که این صفحه در گوگل دیده شود یا خیر', max_length=50, verbose_name='وضعیت نمایش در موتورهای جستجو (SEO)'),
        ),
    ]
