from django.urls import path

from theme.views import main_page_settings
from tour.views.views import *
from tour.views.views_tour import *
from tour.views.views_destination import *
from tour.views.views_flights import *
from tour.views.views_packages import *
from tour.views.views_ajax import *

urlpatterns = [
    # AJAX urls
    path('ajax_airline_list/', ajax_airline_list, name='airline_list'),
    path('ajax_country_list/', ajax_country_list, name='ajax_country_list'),
    path('ajax_city_list/', ajax_city_list, name='ajax_city_list'),
    path('ajax_country_faq_list/', ajax_country_faq_list, name='ajax_country_faq_list'),
    path('ajax_city_media_list/', ajax_city_media_list, name='ajax_city_media_list'),
    path('ajax_country_media_list/', ajax_country_media_list, name='ajax_country_media_list'),
    path('ajax_country_hotel_faq_list/', ajax_country_hotel_faq_list, name='ajax_country_hotel_faq_list'),
    path('ajax_city_faq_list/', ajax_city_faq_list, name='ajax_city_faq_list'),
    path('ajax_city_hotel_faq_list/', ajax_city_hotel_faq_list, name='ajax_city_hotel_faq_list'),
    path('ajax_tour_list/', ajax_tour_list, name='ajax_tour_list'),
    path('ajax_posts_list/', ajax_posts_list, name='ajax_posts_list'),
    path('ajax_order_list/', ajax_order_list, name='ajax_order_list'),
    path('ajax_memories_list/', ajax_memories_list, name='ajax_memories_list'),
    path('ajax_allmsg_list/', ajax_allmsg_list, name='ajax_allmsg_list'),
    path('ajax_airpots_list/', ajax_airpots_list, name='ajax_airpots_list'),
    path('ajax_post_categories/', ajax_post_categories, name='ajax_post_categories'),
    path('ajax_memo_categories/', ajax_memo_categories, name='ajax_memo_categories'),
    path('ajax_tour_categories/', ajax_tour_categories, name='ajax_tour_categories'),
    path('ajax_tour_category_faq_list/', ajax_tour_category_faq_list, name='ajax_tour_category_faq_list'),
    path('ajax_mainPAckages_list/', ajax_main_packages_list, name='ajax_mainPAckages_list'),
    path('ajax_trip_plans/', ajax_trip_plans, name='ajax_trip_plans'),
    path('related_city_ajax/', related_city_ajax, name='related_city_ajax'),
    path('related_tour_ajax/', related_tour_ajax, name='related_tour_ajax'),
    path('packages/', packages, name='packages'),
    path('change_package_price_single/', change_package_price_single, name='change_package_price_single'),
    path('package_hotel_list/', package_hotel_list, name='package_hotel_list'),
    path('', Dashboard, name='dashboard'),
    path('create-currency', create_currency, name='create-currency'),
    path('update-currency/<int:id>', update_currency, name='update-currency'),
    path('delete-currency/<int:id>', delete_currency, name='delete-currency'),

    #destination views
    path('create-country', create_country, name='create-country'),
    path('country_list', country_list, name='country_list'),
    path('update-country/<int:id>', update_country, name='update-country'),
    path('delete-country/<int:id>', delete_country, name='delete-country'),
    path('create-city', create_city, name='create-city'),
    path('city_list', city_list, name='city_list'),
    path('update-city/<int:id>', update_city, name='update-city'),
    path('delete-city/<int:id>', delete_city, name='delete-city'),
    path('create-air-line', create_airline, name='Create-Airline'),
    path('update-air-line/<int:id>', update_airline, name='update-airline'),
    path('delet-airline/<int:id>', delete_airline, name='delet-airline'),
    path('airlines-list/', airline_list, name='airlines-list'),
    path('create-airport', create_airport, name='create-airport'),
    path('update-airport/<int:id>', update_airport, name='update-airport'),
    path('delete-airport/<int:id>', delete_airport, name='delete-airport'),
    path('add_city_to_spacial/<int:id>', add_city_to_spacial, name='add_city_to_spacial'),
    path('update_city_to_spacial/<int:id>', update_city_to_spacial, name='update_city_to_spacial'),
    path('delete_city_to_spacial/<int:id>', delete_city_to_spacial, name='delete_city_to_spacial'),
    path('spacial_destinations_list/', spacial_destinations_list, name='spacial_destinations_list'),
    path('add_country_to_spacial/<int:id>', add_country_to_spacial, name='add_country_to_spacial'),
    path('update_city_to_spacial/<int:id>', update_city_to_spacial, name='update_city_to_spacial'),
    path('delete_city_to_spacial/<int:id>', delete_city_to_spacial, name='delete_city_to_spacial'),

    #tour views
    path('create-tour', create_tour, name='create-tour'),
    path('tour-list', tour_list, name='tour-list'),
    path('update-tour/<int:id>', update_tour, name='update-tour'),
    path('delet-tour/<int:id>', delete_tour, name='delet-tour'),
    path('create-tour-menu', TourMenuCreate, name='create-tour-menu'),
    path('tour-menu-list', TourMenuList, name='tour-menu-list'),
    path('tour-menu-update/<int:id>', TourMenuUpdate, name='tour-menu-update'),
    path('tour-menu-delete/<int:id>', TourMenuDelet, name='tour-menu-delete'),
    path('create-package/', create_package, name='create-package'),
    path('add-to-package/<int:id>', add_to_package, name='add-to-package'),
    path('tour-toggle-pub/<int:id>', toggle_tour_pub, name='tour-toggle-pub'),
    path('update-package/<int:id>', update_package, name='update-package'),
    path('delet-package/<int:id>', delete_package, name='delet-package'),
    path('update-main-package/<int:id>', update_main_packegs, name='update-main-package'),
    path('delete-main-package/<int:id>', delete_main_package, name='delete-main-package'),
    path('tour_date_plan/<int:pk>', tour_date_plan, name='tour_date_plan'),
    path('tour_date_plan_update/<int:id>', tour_date_plan_update, name='tour_date_plan_update'),
    path('tour_date_plan_delete/<int:id>', tour_date_plan_delete, name='tour_date_plan_delete'),
    path('tour_date_plan_hotel_prices/<int:id>', tour_date_plan_hotel_prices, name='tour_date_plan_hotel_prices'),
    path('tour-city-list/<int:pk>', add_city_tour, name='tour-city-list'),
    path('add-related-tour/<int:id>', add_related_tour, name='add_related_tour'),
    path('update-related-tour/<int:id>', update_related_tour, name='update_related_tour'),
    path('delete-related-tour/<int:id>', delete_related_tour, name='delete_related_tour'),
    path('tour-city-update/<int:id>', update_city_tour, name='tour-city-update'),
    path('tour-city-delete/<int:id>', delete_city_tour, name='tour-city-delete'),
    path('create-city-faq/<int:id>', create_city_faq, name='create-city-faq'),
    path('create-tour-category', CreateTourCategory, name='create-tour-category'),
    path('update-tour-category/<int:id>', UpdateTourCategory, name='update-tour-category'),
    path('delete-tour-category/<int:id>', DeleteTourCategory, name='delete-tour-category'),
    path('list-tour-category', ListTourCategory, name='list-tour-category'),
    path('create-tour-category-faq/<int:id>', create_tour_category_faq, name='create-tour-category-faq'),
    path('update-tour-category-faq/<int:id>', update_tour_category_faq, name='update-tour-category-faq'),
    path('delete-tour-category-faq/<int:id>', delete_tour_category_faq, name='delete-tour-category-faq'),
    path('create-media-city/<int:id>', create_media_city, name='create-media-city'),
    path('delete-media-city/<int:id>', delete_media_city, name='delete-media-city'),
    path('update-media-city/<int:id>', update_media_city, name='update-media-city'),
    path('create-media-country/<int:id>', create_media_country, name='create-media-country'),
    path('delete-media-country/<int:id>', delete_media_country, name='delete-media-country'),
    path('update-media-country/<int:id>', update_media_country, name='update-media-country'),
    path('create_city_hotel_faq/<int:id>', create_city_hotel_faq, name='create_city_hotel_faq'),
    path('update_city_hotel_faq/<int:id>', update_city_hotel_faq, name='update_city_hotel_faq'),
    path('delete_city_hotel_faq/<int:id>', delete_city_hotel_faq, name='delete_city_hotel_faq'),
    path('city-faq-delete/<int:id>', delete_city_faq, name='city-faq-delete'),
    path('city-faq-update/<int:id>', update_city_faq, name='city-faq-update'),
    path('copy_tour_data/<int:id>', copy_tour_data, name='copy_tour_data'),
    path('export_tour_packages', export_tour_packages, name='export_tour_packages'),
    path('import_tour_packages', import_tour_packages, name='import_tour_packages'),
    path('change_price_selected_package/', change_price_selected_package, name='change_price_selected_package'),
    path('remove_tour_gallery/<int:id>', remove_tour_gallery, name='remove_tour_gallery'),
    path('remove_tour_featured_image/<int:id>', remove_tour_featured_image, name='remove_tour_featured_image'),
    path('remove_tour_pdf/<int:id>', remove_tour_pdf, name='remove_tour_pdf'),
    path('remove_tour_main_image/<int:id>', remove_tour_main_image, name='remove_tour_main_image'),
    path('add_trip_plan/<int:id>', add_trip_plan, name='add_trip_plan'),
    path('delete_trip_plan/<int:id>', delete_trip_plan, name='delete_trip_plan'),
    path('update_trip_plan/<int:id>', update_trip_plan, name='update_trip_plan'),

    #api partner keys (access we grant to other agencies)
    path('api-partner-list', api_partner_list, name='api-partner-list'),
    path('toggle-api-partner/<int:id>', toggle_api_partner, name='toggle-api-partner'),
    path('delete-api-partner/<int:id>', delete_api_partner, name='delete-api-partner'),

    #template views
    path('create-about', AboutUsCreate, name='create-about'),
    path('update-about/<int:id>', AboutUsUpdate, name='update-about'),
    path('create-contact-us', ContactUsTextCreate, name='create-contact-us'),
    path('update-contact-us/<int:id>', ContactUsTextUpdate, name='update-contact-us'),
    path('create-slideshow/<int:id>', CreateSlideShow, name='create-slideshow'),
    path('messages', ContactUsInbox, name='messages'),
    path('message_delete/<int:id>', message_delete, name='message_delete'),

    #memory views
    path('memo-list', MemoriesList, name='memo-list'),
    path('create-memory', memoriesCreate, name='create-memory'),
    path('memo-update/<int:id>', memoriesUpdate, name='memo-update'),
    path('memo-delete/<int:id>', memoriesDelete, name='memo-delete'),
    path('create-memo-category', CreateMemoryCategory, name='create-memo-category'),
    path('update-memo-category/<int:id>', UpdateMemoryCategory, name='update-memo-category'),
    path('delete-memo-category/<int:id>', DeleteMemoryCategory, name='delete-memo-category'),
    path('memo-category-list', MemoCategoryList, name='memo-category-list'),
    path('export-contacts', export_contacts_csv, name='export-contacts'),
    path('export-numbers', export_numbers_csv, name='export-numbers'),
    path('subscribe-list', subscribeList, name='subscribe'),
    path('delete-subscribe/<int:id>', subscribeDelete, name='sub-delete'),
    path('footer/<int:id>', FooterUpdate, name='footer'),
    path('update-dollar-rate', update_dollar_rate, name='update-dollar-rate'),
    path('tour-interest-list', tour_interest_list, name='tour-interest-list'),
    path('delete-tour-interest/<int:id>', delete_tour_interest, name='delete-tour-interest'),
    path('tour-review-list', tour_review_list, name='tour-review-list'),
    path('tour-review-create', tour_review_create, name='tour-review-create'),
    path('tour-review-update/<int:id>', tour_review_update, name='tour-review-update'),
    path('tour-review-delete/<int:id>', tour_review_delete, name='tour-review-delete'),
    path('tour-review-fetch-google', tour_review_fetch_google, name='tour-review-fetch-google'),
    path('tour-review-import-google', tour_review_import_google, name='tour-review-import-google'),
    path('order-list', OrderInbox, name='order-list'),
    path('order-update/<int:id>', OrderUpdate, name='order-update'),
    path('order-delete/<int:id>', OrderDelete, name='order-delete'),
    path('create-faq/<int:id>', create_country_faq, name='create-faq'),
    path('create-faq-hotel/<int:id>', create_hotel_country_faq, name='create_hotel_country_faq'),
    path('faq-update/<int:id>', update_country_faq, name='faq-update'),
    path('faq-update-hotel/<int:id>', update_country_hotel_faq, name='update_country_hotel_faq'),
    path('faq-delete/<int:id>', delete_country_faq, name='faq-delete'),
    path('faq-delete-hotel/<int:id>', delete_country_hotel_faq, name='delete_country_hotel_faq'),
    path('faq-list/<int:id>', country_faq_list, name='faq-list'),
    path('faq-list-hotel/<int:id>', country_hotel_faq_list, name='country_hotel_faq_list'),


    path('create_home_faq', create_home_faq, name='create_home_faq'),
    path('update_home_faq/<int:id>', update_home_faq, name='update_home_faq'),
    path('delete_home_faq/<int:id>', delete_home_faq, name='delete_home_faq'),
    path('main_page_settings/<int:id>', main_page_settings, name='main_page_settings'),
]
