from django.contrib.auth.models import User
from django.db import models

class visa_request_item(models.Model):
    STAT = [
        ('Submitted','Submitted'),('Checking','Checking'),('Confirmed','Confirmed'), ('Processing','Processing'), ('Approved','Approved')
    ]
    GND = [
        ('Male', 'Male'),('Female', 'Female')
    ]
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True, blank=True)
    trs_number = models.CharField(max_length=10, null=True, blank=True)
    requester_name = models.CharField(max_length=100, verbose_name='Requseter Name')
    requester_family = models.CharField(max_length=100, verbose_name='Requster Family')
    requester_id_number = models.CharField(max_length=100, null=True, blank=True)
    rq_father_name = models.CharField(max_length=100, verbose_name='Father Name')
    rq_father_family = models.CharField(max_length=100, verbose_name='Father Family')
    rq_father_brd = models.DateField(verbose_name='Father Brithday')
    rq_father_brd_location = models.CharField(max_length=100, verbose_name='Father Birth Location')
    rq_mother_name = models.CharField(max_length=100, verbose_name='Mother Name')
    rq_mother_family = models.CharField(max_length=100, verbose_name='Father Family')
    rq_mother_brd = models.DateField(verbose_name='Mother Brithday')
    rq_mother_brd_location = models.CharField(max_length=100, verbose_name='Mother Birth Location')
    address = models.CharField(max_length=300, verbose_name='Requester Address')
    phone = models.CharField(max_length=20, verbose_name='Requester Phone')
    email = models.CharField(max_length=100, verbose_name='Requester E-mail')
    job_title = models.CharField(max_length=100, verbose_name='Job Title')
    job_address = models.CharField(max_length=300, verbose_name='Job Address')
    job_phone = models.CharField(max_length=20, verbose_name='Job Phone')
    job_email = models.CharField(max_length=100, verbose_name='Job E-mail')
    passport_image = models.ImageField(upload_to='media/visa/passport', null=True, blank=True, verbose_name='Passport Image')
    person_image = models.ImageField(upload_to='media/visa/person', null=True, blank=True, verbose_name='Requester Image')
    visa_file = models.FileField(upload_to='media/visa/resualt', null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    old_name = models.CharField(max_length=100, null=True, blank=True)
    name_change_date = models.CharField(max_length=100, null=True, blank=True)
    name_change_reason = models.CharField(max_length=100, null=True, blank=True)
    cz_country = models.CharField(max_length=100, null=True, blank=True)
    cz_passport = models.CharField(max_length=18, null=True, blank=True, verbose_name='Passport Number')
    gc_country = models.CharField(max_length=100, null=True, blank=True)
    gc_start_date = models.CharField(max_length=11, null=True, blank=True)
    gc_end_date = models.CharField(max_length=50, null=True, blank=True)
    gc_id_number = models.CharField(max_length=20, null=True, blank=True)
    travel_history = models.CharField(max_length=300, null=True, blank=True)
    social_media = models.CharField(max_length=100, null=True, blank=True)
    partner_name = models.CharField(max_length=100, null=True, blank=True)
    partner_family = models.CharField(max_length=100, null=True, blank=True)
    partner_brd_date = models.CharField(max_length=11, null=True, blank=True)
    partner_brd_location = models.CharField(max_length=100, null=True, blank=True)
    uni_name = models.CharField(max_length=100, null=True, blank=True)
    uni_address = models.CharField(max_length=200, null=True, blank=True)
    military_start_date = models.CharField(max_length=20,null=True, blank=True)
    military_end_date = models.CharField(max_length=20,null=True, blank=True)
    military_type = models.CharField(max_length=100, null=True, blank=True)
    military_location = models.CharField(max_length=100, null=True, blank=True)
    travel_reason = models.CharField(max_length=500, null=True, blank=True)
    hotel_name = models.CharField(max_length=300, null=True, blank=True)
    passport_issue = models.DateField(null=True, blank=True)
    passport_expire = models.DateField(null=True, blank=True)
    data_entry_russia = models.DateField(null=True, blank=True)
    relation_degree = models.CharField(max_length=150, null=True, blank=True)
    relation_name = models.CharField(max_length=150, null=True, blank=True)
    relation_family = models.CharField(max_length=150, null=True, blank=True)
    relation_sex = models.CharField(max_length=150, null=True, blank=True)
    relation_Address = models.CharField(max_length=150, null=True, blank=True)
    relation_brd_date = models.CharField(max_length=20,null=True, blank=True)
    relation_phone = models.CharField(max_length=20,null=True, blank=True)
    orogin_name = models.CharField(max_length=150, null=True, blank=True)
    orogin_address = models.CharField(max_length=150, null=True, blank=True)
    orogin_phone = models.CharField(max_length=50, null=True, blank=True)
    orogin_email = models.CharField(max_length=50, null=True, blank=True)
    orogin_city = models.CharField(max_length=50, null=True, blank=True)
    confirmed = models.BooleanField(default=False)
    req_stat = models.CharField(choices=STAT, null=True, blank=True, max_length=100)
    gender = models.CharField(max_length=100,null=True, blank=True)
    payment_stat = models.BooleanField(default=False)
    marial_stat = models.BooleanField(default=False)
    russia_relative_stat = models.BooleanField(default=False)
    uni_degree_stat = models.BooleanField(default=False)


class ThaiVisa(models.Model):
    STAT = [
        ('Submitted','Submitted'),('Checking','Checking'),('Confirmed','Confirmed'),
        ('Processing','Processing'), ('Approved','Approved')
    ]
    GND = [
        ('Male', 'Male'),('Female', 'Female')
    ]
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True, blank=True)
    trs_number = models.CharField(max_length=10, null=True, blank=True)
    gender = models.CharField(max_length=100,null=True, blank=True)
    requester_name = models.CharField(max_length=100)
    requester_family = models.CharField(max_length=100)
    rqquester_brd = models.DateField()
    requester_Nationality = models.CharField(max_length=100)
    requester_brd_city = models.CharField(max_length=100)
    requester_country = models.CharField(max_length=100)
    requester_city = models.CharField(max_length=100)
    address = models.CharField(max_length=300)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=100)
    passport_number = models.CharField(max_length=100,null=True, blank=True)
    passport_issue = models.DateField(null=True, blank=True)
    passport_expire = models.DateField(null=True, blank=True)
    thai_entry = models.DateField(null=True, blank=True)
    thai_exit = models.DateField(null=True, blank=True)
    marial_stat = models.BooleanField(default=False)
    job_title = models.CharField(max_length=100)
    job_company = models.CharField(max_length=100)
    income = models.CharField(max_length=100)
    job_owner = models.BooleanField(default=False)
    thai_trip = models.BooleanField(default=False)
    thai_applied = models.BooleanField(default=False)
    inviter_name = models.CharField(max_length=100, null=True, blank=True)
    inviter_city = models.CharField(max_length=100, null=True, blank=True)
    inviter_phone = models.CharField(max_length=100, null=True, blank=True)
    inviter_email = models.CharField(max_length=100, null=True, blank=True)
    inviter_address = models.CharField(max_length=300, null=True, blank=True)
    passport_image = models.ImageField(upload_to='media/visa/thai/passport', null=True, blank=True)
    person_image = models.ImageField(upload_to='media/visa/thai/person', null=True, blank=True)
    person_brd_image = models.ImageField(upload_to='media/visa/thai/brd', null=True, blank=True)
    person_id_image = models.ImageField(upload_to='media/visa/thai/idcard', null=True, blank=True)
    person_hotel_image = models.ImageField(upload_to='media/visa/thai/hotel', null=True, blank=True)
    person_flight_image = models.ImageField(upload_to='media/visa/thai/flight', null=True, blank=True)
    confirmed = models.BooleanField(default=False)
    req_stat = models.CharField(choices=STAT, null=True, blank=True, max_length=100)
    visa_file = models.FileField(upload_to='media/visa/thai/resualt', null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    payment_stat = models.BooleanField(default=False)