# Generated by Django 5.0.2 on 2024-08-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_ticket', models.BooleanField(default=True)),
                ('external_ticket', models.BooleanField(default=True)),
                ('hotel_reserve', models.BooleanField(default=True)),
                ('st_title', models.CharField(max_length=300)),
                ('about_title', models.CharField(max_length=300)),
                ('about_text', models.TextField(max_length=5000)),
                ('about_logo', models.ImageField(upload_to='media/index_page')),
                ('about_address', models.CharField(max_length=300)),
                ('about_phone', models.CharField(max_length=300)),
                ('blog_title', models.CharField(max_length=300)),
                ('faq_title', models.CharField(max_length=300)),
                ('box_1_title', models.CharField(max_length=100)),
                ('box_2_title', models.CharField(max_length=100)),
                ('box_3_title', models.CharField(max_length=100)),
                ('box_1_desc', models.CharField(max_length=100)),
                ('box_2_desc', models.CharField(max_length=100)),
                ('box_3_desc', models.CharField(max_length=100)),
                ('footer_phone', models.CharField(max_length=100)),
                ('footer_address', models.CharField(max_length=300)),
            ],
        ),
    ]
