# Generated by Django 5.0.2 on 2024-08-19 14:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_page',
            name='about_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000, null=True),
        ),
    ]
