# Generated by Django 5.0.2 on 2026-09-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_alter_index_page_about_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_page',
            name='google_review_url',
            field=models.URLField(blank=True, help_text='از Google Business Profile بخش Ask for reviews کپی کنید', max_length=500, null=True, verbose_name='لینک ثبت نظر در گوگل'),
        ),
    ]
