# Generated by Django 5.0.2 on 2026-09-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_index_page_google_review_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_page',
            name='google_api_proxy',
            field=models.CharField(blank=True, help_text='مثل http://127.0.0.1:10809 وقتی سرور مستقیم به گوگل وصل نمی\u200cشود', max_length=200, null=True, verbose_name='پراکسی درخواست به گوگل (اختیاری)'),
        ),
        migrations.AddField(
            model_name='index_page',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='از صفحهٔ Place ID Finder گوگل کپی کنید', max_length=200, null=True, verbose_name='شناسهٔ مکان در گوگل (Place ID)'),
        ),
        migrations.AddField(
            model_name='index_page',
            name='google_places_key',
            field=models.CharField(blank=True, help_text='در Google Cloud باید Places API (New) فعال باشد', max_length=200, null=True, verbose_name='کلید Places API'),
        ),
    ]
