# Generated by Django 5.0.2 on 2024-08-09 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=10, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_total', models.IntegerField(blank=True, default=0, null=True)),
                ('paid_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('discount_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(auto_now_add=True)),
                ('order_close', models.BooleanField(default=False)),
                ('dicount_copon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.IntegerField(default=2)),
                ('adults_price', models.IntegerField(default=0)),
                ('baby_with_bed', models.IntegerField(default=0)),
                ('baby_with_bed_price', models.IntegerField(default=0)),
                ('baby_with_out_bed', models.IntegerField(default=0)),
                ('baby_with_out_bed_price', models.IntegerField(default=0)),
                ('infont', models.IntegerField(default=0)),
                ('infont_price', models.IntegerField(default=0)),
                ('total_item_price', models.IntegerField(default=0)),
                ('item_add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.package')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='orderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('payment_stat', models.BooleanField(default=False)),
                ('payment_refId', models.CharField(blank=True, max_length=10, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
