SERVICE_ICONS = {
    # HOTEL_SERVICES
    'پارکینگ': 'local_parking',
    'آسانسور': 'elevator',
    'شاتل': 'shuttle',
    'ترانسفر فرودگاهی': 'airport_shuttle',
    'فروشگاه در محل': 'storefront',
    'فروشگاه در هتل': 'storefront',
    'نزدیک به فرودگاه': 'flight_takeoff',
    'نزدیک به ساحل': 'beach_access',
    'فضای سبز': 'park',
    'ساحل اختصاصی': 'beach_access',
    'اینترنت رایگان در لابی': 'wifi',
    'سالن کنفرانس': 'meeting_room',
    'سالن همایش': 'event_available',
    'اجاره ماشین': 'directions_car',
    'انبار چمدان': 'luggage',
    'رستوران': 'restaurant',
    'کافی شاپ': 'coffee',
    'صرافی': 'currency_exchange',
    'محل مخصوص سیگار کشیدن': 'smoking_rooms',
    'اتاق خانوادگی': 'family_restroom',
    'محل سیگار ممنوع': 'smoke_free',
    'امکانات برای معلولین': 'accessible',
    'لپ تاپ': 'laptop',
    'ورود حیوانات مجاز': 'pets',
    
    # ROOM_SERVICES
    'اینترنت رایگان در اتاق': 'wifi',
    'تراس/بالکن': 'balcony',
    'چای/قهوه ساز': 'coffee_maker',
    'وان': 'bathtub',
    'صندوق امانات': 'safe',
    'کمد و جالباسی': 'closet',
    'تهویه مطبوع': 'ac_unit',
    'حوله و دمپایی': 'dry',
    'سشوار': 'dry',
    'اتو': 'iron',
    'سنسور دودیاب/ضد حریق': 'sensors',
    'آلارم بیدار باش': 'alarm',
    'سیستم گرمایش': 'thermostat',
    'تلوزیون/ماهواره': 'tv',
    'عایق صدا': 'volume_mute',
    'میز مطالعه': 'desk',
    'نور گیر': 'blinds',
    'دزدگیر': 'security',
    'منظره شهری': 'location_city',
    'آشپزخانه': 'kitchen',
    'لوازم بهداشتي': 'bathroom',
    
    # SERVICES
    'سرویس اتاق 24 ساعته': 'room_service',
    'صبحانه در اتاق': 'breakfast_dining',
    'خدمات پزشکی': 'medical_services',
    'خشکشویی': 'local_laundry_service',
    'نظافت روزانه': 'cleaning_services',
    'پذیرش 24 ساعته': 'support_agent',
    'غذای کودک': 'baby_changing_station',
    'غذای رژیمی': 'restaurant_menu',
    'صبحانه': 'free_breakfast',
    'خدمات زیبایی': 'spa',
    
    # INTERTAINMENT
    'استخر روباز': 'pool',
    'استخر سرپوشیده': 'pool',
    'سونا/جکوزی': 'hot_tub',
    'پارک آبی': 'water',
    'حمام ترکی': 'sauna',
    'ماساژ': 'spa',
    'مینی بار': 'minibar',
    'مرکز اسپا و سلامتی': 'spa',
    'استخر کودک': 'child_care',
    'سالن بازی کودکان': 'sports_esports',
    'پارک کودک': 'park',
    'تفريحات آبي': 'water',
    'قايقراني': 'kayaking',
    'غواصی': 'diving',
    'سالن بدنسازی': 'fitness_center',
    'بیلیارد': 'sports_billiards',
    'دارت': 'sports_esports',
    'تنیس': 'sports_tennis',
    'کلاس یوگا': 'self_improvement',
    'سولاريوم': 'wb_sunny',
    'ماهيگيري': 'fishing',
    'اسنک بار': 'bakery_dining',
    'اتاق گیم': 'sports_esports',
    'بار': 'local_bar', 
    'پینگ پونگ': 'sports_table_tennis',
    'بولینگ': 'bowling',
    'اسکی': 'downhill_skiing',
    'اجراي برنامه هاي شاد': 'celebration', 
    'موسیقی زنده': 'music_note',
    'دی جی': 'queue_music', 
    'دوچرخه سواری': 'pedal_bike',
    'گلف': 'golf_course',
    'کارائوکه': 'mic',
    'صندلی ساحلی': 'beach_access',
    'کلوپ شبانه': 'night_shelter', 
}

def get_icon_name(service_name):
    return SERVICE_ICONS.get(service_name, 'check_circle')